# See https://github.com/gitconsensus/GitConsensusCLI for more information about this file.

version: 3

# Don't count any vote from a user who votes for multiple options
prevent_doubles: true

# Add extra labels for the vote counts and age when merging
extra_labels: true


pull_requests:

  # How many votes (including abstains) that are required.
  quorum: 10

  # Required percentage of "yes" votes (ignoring abstentions). It's a good idea to give "no" votes more power.
  threshold: 0.74

  # Number of hours after last action (commit or opening the pull request) before issue can be merged
  # 15 days.
  merge_delay: 375

  # Number of hours at which the merge_delay gets ignored, assuming no negative votes.
  # 10 Days.
  delay_override: 240

  # Close pull requests that don't pass after thirty days without any activity (new commits).
  # 60 days.
  timeout: 1440

  # We do not allow changes to the license.
  license_lock: true

  # We do allow the consensus rules (this file) to be changed.
  consensus_lock: false

  # How long before merging any new consensus rules.
  # 15 Days
  consensus_delay: 375

  # Allow anyone to vote on this project, even if they've never contributed.
  contributors_only: false

  # Don't put any restrictions on who can vote.
  collaborators_only: false
